jobs:
  build:
    working_directory: ~/ex_rlp
    docker:
      - image: elixir:latest
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - restore_cache:
          keys:
            - v2-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v2-dependency-cache-{{ arch }}
            - v2-dependency-cache

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted
      - run:
          command: mix compile
          environment:
            MIX_ENV: test

      - save_cache:
          key: v2-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - run: mix test

      - restore_cache:
          keys:
            - v2-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v2-plt-cache-{{ arch }}
            - v2-plt-cache

      - run: mix dialyzer --plt

      - save_cache:
          key: v2-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix

      - run: mix dialyzer  --halt-exit-status
